apiVersion: 1

datasources:
  - name: Broiler InfluxDB
    type: influxdb
    access: proxy
    url: http://host.docker.internal:8086
    database: broiler_telemetry
    isDefault: true
    editable: true
