spring.application.name=broiler_monitoring
server.port=8080
spring.config.import=optional:file:.env[.properties]



spring.datasource.url=jdbc:postgresql://127.0.0.1:${POSTGRES_PORT:5434}/${POSTGRES_DB:broiler_monitoring}
spring.datasource.username=${POSTGRES_USER:broiler_user}
spring.datasource.password=${POSTGRES_PASSWORD:broiler_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

telemetry.influx.url=http://localhost:8086
telemetry.influx.database=broiler_telemetry

sensor.simulation.enabled=true
sensor.simulation.target-url=http://localhost:8080/api/v1/telemetry/readings
TELEMETRY_INFLUX_URL=http://localhost:8086
sensor.simulation.gateway-id=GW-FARM-1-HOUSE-4
sensor.simulation.interval-ms=600000
sensor.simulation.initial-delay-ms=15000

